# Generated by Django 5.2.6 on 2025-09-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_Attendance_Manager_Models', '0003_remove_attendance_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('checkout', 'Checkout')], default='present', max_length=10),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
