# Generated by Django 5.2.6 on 2025-09-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_Attendance_Manager_Models', '0004_alter_attendance_status_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('checkout', 'Checkout'), ('day_finished', 'Day Finished')], default='present', max_length=15),
        ),
    ]
