# Generated by Django 5.1.5 on 2025-09-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_Attendance_Manager_Models', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Time when student checked in', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Time when student checked out', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_time_spent',
            field=models.DurationField(blank=True, help_text='Total time spent in class (calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('checkout', 'Checkout'), ('day_finished', 'Day Finished'), ('day_locked', 'Day Locked')], default='present', max_length=15),
        ),
    ]
